networks:
  app-tier:
    driver: bridge
  db-net:
    driver: bridge

services:
  exchange-rate-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-rate-service
    ports:
      - "9049:9049"
    networks:
      - db-net
    environment:
      CONFIG_PATH: config/docker.yml
    restart: unless-stopped
    depends_on:
      - postgresql

  postgresql:
    image: docker.io/postgres:16.3
    container_name: postgresql-exrate
    ports:
      - "5432:5432"
    networks:
      - db-net
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: exchangerate
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d exchangerate" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s